CREATE TABLE HabbitOne (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL,
day INT NOT NULL
)

CREATE TABLE HabbitTwo (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL,
day INT NOT NULL
)

CREATE TABLE HabbitThree (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL,
day INT NOT NULL
)

CREATE TABLE HabbitFour (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL,
day INT NOT NULL
)

CREATE TABLE HabbitFive (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL,
day INT NOT NULL
)